### ISSUE TITLE
mixed naming conventions & code ethics

### ISSUE THREAD

**Issue by okarem** [WebAhead5/SmartCooking#9]
https://github.com/WebAhead5/SmartCooking/blob/14922b52a9ba3c743b21b4ecb2035cda1b578771/script.js#L35

 **please choose meaningful names for your variables**
while RecipeMang  is a legal name in JS, it's not clear what it means and other people who will work on your code in the real world would not understand what it refers to.
aRecipiesListToPutInTheDomeViaRenderingNewElementForEachOne is also a legal name in JS but it's clearer (i don't actually suggest using it, it's just to show that you shouldn't use shertend unclear names)
a clear, readable uncommented code is many folds better than a commented mess.

**some naming conventions** :
camel case (widely used in javascript code) : recipiesList 
kebab case: recipies-list
pascal case: RecipieList
lizard case: recipie_list
please choose one and stick to it (i would suggest camel case for javascript)

**Comment by amirfahoum** [comment]
Done:)
